### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by tkovacik** [veizz/react-native-picker-scrollview#2]
Used your example and after opening app this error is thrown. Any ideas?

**Comment by veizz** [comment]
some details of you error?

**Comment by anztrax** [comment]
thats because of `PropTypes` is already removed from `react` version that you used @tkovacik , you can use react version that `PropTypes` inside `react` . or you can pull request to @veizz  

thanks   🎉

**Comment by jamesbuckley1** [comment]
Same issue.

<img width="392" alt="screen shot 2018-10-03 at 13 12 28" src="https://user-images.githubusercontent.com/32818878/46409579-06a8de80-c70e-11e8-9a36-c1794d2c2658.png">

**Comment by veizz** [comment]
PropType was moved to [prop-types](https://www.npmjs.com/package/prop-types), and View.propTypes was moved to ViewPropTypes [53905a5](https://github.com/facebook/react-native/commit/53905a537a58d028fc5eb1c4e9a8ec967d8cd396)

I published a new version, try `npm install  react-native-picker-scrollview@1` please.
