### ISSUE TITLE
Scroll view exceeds or falls short to view the list of elements.

### ISSUE THREAD

**Issue by sdv1812** [veizz/react-native-picker-scrollview#5]
Hi, 
I am working with expo to build react native elements and found this beautiful pure js library for iOS like wheel picker. However I am facing this issue: 

On some phone models with the list of items scrolls more than it should. Whereas on other phones it is not able to scroll to the end of the list and hence not able to select the last item. 

Here are the screen shots to explain the situation:

Here (Asus Z00LD) i am able to select blank/undefined items from the list as it has scrolled more than it should have. 
![screenshot_20190306-113046](https://user-images.githubusercontent.com/17542031/53854653-4f3e2e00-4005-11e9-81a0-a3523711be82.jpg)

Here (Samsung A7) i am not able to scroll down until the end and hence not able to select '71 - 100'

![screenshot_20190306-104259_expo](https://user-images.githubusercontent.com/17542031/53854810-e60aea80-4005-11e9-85fa-9aea0452a75a.jpg)

Here is the code for same: 
```
<ScrollPicker 
    ref={(sp) => { this.sp = sp; }}
    dataSource={this.props.ageGroups}
    selectedIndex={0}
    itemHeight={50}
    wrapperHeight={250}
        highlightColor={'#d8d8d8'}
        renderItem={(data, index, isSelected) => {
          if (isSelected) {
            return (
              <View>
                  <LargeText bold>{data}</LargeText>
              </View>
            );
          }
            return (
                <View>
                    <MediumText>{data}</MediumText>
                </View>
            );
        }}
        onValueChange={(data, selectedIndex) => {
          console.log(data, selectedIndex);
          this.props.selectAgeGroup({ ageGroup: data });
        }}
      />
```

this.props.ageGroups = [
    '1 - 10',
    '11 - 20',
    '21 - 30',
    '31 - 40',
    '41 - 50',
    '51 - 60',
    '61 - 70',
    '71 - 100',
  ];

How to dynamically adjust the height of scroll view? Is it dependent on `lineHeight` and `wrapperHeight`?

**Comment by sdv1812** [comment]
As a workaround I have increased the `wrapperHeight` to 300 and changed the onValueChange function to 
```
onValueChange={(data, selectedIndex) => {
          if (selectedIndex >= this.props.ageGroups.length) {
            this.sp.scrollToIndex(this.props.ageGroups.length - 1);
            data = this.props.ageGroups[this.props.ageGroups.length - 1];
          }
          this.props.selectAgeGroup({ ageGroup: data });
        }}
```

**Comment by veizz** [comment]
sorry, haven't run into this before, no idea...  

the height is calculated from `itemHeight` and `wrapperHeight`

```
this.itemHeight = this.props.itemHeight || 30;
this.wrapperHeight = this.props.wrapperHeight || (this.props.style ? this.props.style.height : 0) ||this.itemHeight * 5;
```
